-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USU_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USU_USUARIO` (
  `USU_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `USU_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `USU_SENHA` VARCHAR(45) NOT NULL COMMENT '',
  `USU_TIPO` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`USU_CODIGO`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOG_LOGIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOG_LOGIN` (
  `LOG_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `LOG_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `LOG_SENHA` VARCHAR(45) NOT NULL COMMENT '',
  `LOG_TIPO` INT(11) NOT NULL COMMENT '',
  `USU_CODIGO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`LOG_CODIGO`)  COMMENT '',
  INDEX `fk_LOG_LOGIN_USU_USUARIO_idx` (`USU_CODIGO` ASC)  COMMENT '',
  CONSTRAINT `fk_LOG_LOGIN_USU_USUARIO`
    FOREIGN KEY (`USU_CODIGO`)
    REFERENCES `mydb`.`USU_USUARIO` (`USU_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DES_DESPESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DES_DESPESA` (
  `DES_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DES_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `DES_VALOR` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`DES_CODIGO`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORD_ORDEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORD_ORDEM` (
  `ORD_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ORD_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `ORD_DATAINICIO` DATE NOT NULL COMMENT '',
  `ORD_DATAEXPIRACAO` DATE NOT NULL COMMENT '',
  `ORD_QUANTIDADE` INT NOT NULL COMMENT '',
  `ORD_FUNCIONARIO` VARCHAR(255) NOT NULL COMMENT '',
  `ORD_DESCRICAO` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`ORD_CODIGO`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUS_CUSTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUS_CUSTO` (
  `CUS_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `CUS_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `CUS_VALOR` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`CUS_CODIGO`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOT_LOTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOT_LOTE` (
  `LOT_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `LOT_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `LOT_QUANTIDADE` INT(11) NOT NULL COMMENT '',
  `LOT_DESCRICAO` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`LOT_CODIGO`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLI_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLI_CLIENTE` (
  `CLI_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `CLI_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `CLI_ENDERECO` VARCHAR(255) NOT NULL COMMENT '',
  `CLI_BAIRRO` VARCHAR(255) NOT NULL COMMENT '',
  `CLI_NUMERO` INT(10) NOT NULL COMMENT '',
  `CLI_CNPJ` VARCHAR(255) NOT NULL COMMENT '',
  `CLI_TELEFONE` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`CLI_CODIGO`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VEN_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VEN_VENDA` (
  `VEN_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `VEN_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `VEN_DATA` DATE NOT NULL COMMENT '',
  `VEN_QUANTIDADE` INT(11) NOT NULL COMMENT '',
  `CLI_CODIGO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`VEN_CODIGO`)  COMMENT '',
  INDEX `fk_VEN_VENDA_CLI_CLIENTE1_idx` (`CLI_CODIGO` ASC)  COMMENT '',
  CONSTRAINT `fk_VEN_VENDA_CLI_CLIENTE1`
    FOREIGN KEY (`CLI_CODIGO`)
    REFERENCES `mydb`.`CLI_CLIENTE` (`CLI_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRO_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRO_PRODUTO` (
  `PRO_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `PRO_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `PRO_VALOR` DOUBLE NOT NULL COMMENT '',
  `PRO_QUANTIDADE` INT(11) NOT NULL COMMENT '',
  `PRO_DESCRICAO` VARCHAR(255) NOT NULL COMMENT '',
  `PRO_FOTO` VARCHAR(255) NOT NULL DEFAULT 'DEFAULT NULL' COMMENT '',
  `DES_CODIGO` INT NOT NULL COMMENT '',
  `ORD_CODIGO` INT NOT NULL COMMENT '',
  `CUS_CODIGO` INT NOT NULL COMMENT '',
  `LOT_CODIGO` INT NOT NULL COMMENT '',
  `VEN_CODIGO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`PRO_CODIGO`)  COMMENT '',
  INDEX `fk_PRO_PRODUTO_DES_DESPESA1_idx` (`DES_CODIGO` ASC)  COMMENT '',
  INDEX `fk_PRO_PRODUTO_ORD_ORDEM1_idx` (`ORD_CODIGO` ASC)  COMMENT '',
  INDEX `fk_PRO_PRODUTO_CUS_CUSTO1_idx` (`CUS_CODIGO` ASC)  COMMENT '',
  INDEX `fk_PRO_PRODUTO_LOT_LOTE1_idx` (`LOT_CODIGO` ASC)  COMMENT '',
  INDEX `fk_PRO_PRODUTO_VEN_VENDA1_idx` (`VEN_CODIGO` ASC)  COMMENT '',
  CONSTRAINT `fk_PRO_PRODUTO_DES_DESPESA1`
    FOREIGN KEY (`DES_CODIGO`)
    REFERENCES `mydb`.`DES_DESPESA` (`DES_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRO_PRODUTO_ORD_ORDEM1`
    FOREIGN KEY (`ORD_CODIGO`)
    REFERENCES `mydb`.`ORD_ORDEM` (`ORD_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRO_PRODUTO_CUS_CUSTO1`
    FOREIGN KEY (`CUS_CODIGO`)
    REFERENCES `mydb`.`CUS_CUSTO` (`CUS_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRO_PRODUTO_LOT_LOTE1`
    FOREIGN KEY (`LOT_CODIGO`)
    REFERENCES `mydb`.`LOT_LOTE` (`LOT_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRO_PRODUTO_VEN_VENDA1`
    FOREIGN KEY (`VEN_CODIGO`)
    REFERENCES `mydb`.`VEN_VENDA` (`VEN_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PER_PERDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PER_PERDA` (
  `PER_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `PER_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `PER_QUANTIDADE` INT(11) NOT NULL COMMENT '',
  `PER_DESCRICAO` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`PER_CODIGO`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MET_META`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MET_META` (
  `MET_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `MET_NOME` VARCHAR(255) NOT NULL COMMENT '',
  `MET_MES` DATE NOT NULL COMMENT '',
  `MET_ANO` DATE NOT NULL COMMENT '',
  `MET_DESCRICAO` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`MET_CODIGO`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EST_ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EST_ESTOQUE` (
  `EST_CODIGO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `EST_NOME` VARCHAR(45) NOT NULL COMMENT '',
  `EST_QUANTIDADE` INT(11) NOT NULL COMMENT '',
  `EST_DESCRICAO` VARCHAR(255) NOT NULL COMMENT '',
  `PRO_CODIGO` INT NOT NULL COMMENT '',
  `PER_CODIGO` INT NOT NULL COMMENT '',
  `MET_CODIGO` INT NOT NULL COMMENT '',
  `VEN_CODIGO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`EST_CODIGO`)  COMMENT '',
  INDEX `fk_EST_ESTOQUE_PRO_PRODUTO1_idx` (`PRO_CODIGO` ASC)  COMMENT '',
  INDEX `fk_EST_ESTOQUE_PER_PERDA1_idx` (`PER_CODIGO` ASC)  COMMENT '',
  INDEX `fk_EST_ESTOQUE_MET_META1_idx` (`MET_CODIGO` ASC)  COMMENT '',
  INDEX `fk_EST_ESTOQUE_VEN_VENDA1_idx` (`VEN_CODIGO` ASC)  COMMENT '',
  CONSTRAINT `fk_EST_ESTOQUE_PRO_PRODUTO1`
    FOREIGN KEY (`PRO_CODIGO`)
    REFERENCES `mydb`.`PRO_PRODUTO` (`PRO_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EST_ESTOQUE_PER_PERDA1`
    FOREIGN KEY (`PER_CODIGO`)
    REFERENCES `mydb`.`PER_PERDA` (`PER_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EST_ESTOQUE_MET_META1`
    FOREIGN KEY (`MET_CODIGO`)
    REFERENCES `mydb`.`MET_META` (`MET_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EST_ESTOQUE_VEN_VENDA1`
    FOREIGN KEY (`VEN_CODIGO`)
    REFERENCES `mydb`.`VEN_VENDA` (`VEN_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
