-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 12:54:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_bfg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_bfg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_bfg` DEFAULT CHARACTER SET latin1 ;
USE `bd_bfg` ;

-- -----------------------------------------------------
-- Table `bd_bfg`.`giro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`giro` (
  `gir_codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `gir_produto` VARCHAR(255) NOT NULL,
  `gir_estoqueMaximo` INT(11) NOT NULL,
  `gir_estoqueMinimo` INT(11) NULL DEFAULT NULL,
  `gir_estoqueMedio` INT(11) NULL DEFAULT NULL,
  `gir_estoqueAtual` INT(11) NULL DEFAULT NULL,
  `gir_vendas` INT(11) NOT NULL,
  PRIMARY KEY (`gir_codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_bfg`.`log_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`log_login` (
  `LOG_CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
  `LOG_NOME` VARCHAR(255) NOT NULL,
  `LOG_SENHA` VARCHAR(45) NOT NULL,
  `LOG_TIPO` INT(11) NOT NULL,
  `USU_CODIGO` INT(11) NOT NULL,
  PRIMARY KEY (`LOG_CODIGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_bfg`.`met_metas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`met_metas` (
  `met_codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `met_mes` VARCHAR(45) NOT NULL,
  `met_ano` VARCHAR(45) NOT NULL,
  `met_meta` INT(11) NOT NULL,
  `met_produto` VARCHAR(45) NOT NULL,
  `met_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`met_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_bfg`.`per_perda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`per_perda` (
  `per_codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `per_ordem` INT(11) NOT NULL,
  `per_produto` VARCHAR(45) NOT NULL,
  `per_quantidade` INT(11) NOT NULL,
  `per_motivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`per_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_bfg`.`tbl_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`tbl_estoque` (
  `est_codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `est_dataMovimento` VARCHAR(45) NOT NULL,
  `est_codigoProduto` INT(11) NOT NULL,
  `est_descricaoProduto` VARCHAR(255) NULL DEFAULT NULL,
  `est_tipoMovimento` VARCHAR(45) NOT NULL,
  `est_quantidade` INT(11) NOT NULL,
  `est_estoqueAtual` INT(11) NOT NULL,
  PRIMARY KEY (`est_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_bfg`.`tbl_os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`tbl_os` (
  `os_codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `os_quantidade` INT(11) NOT NULL,
  `os_produto` VARCHAR(45) NOT NULL,
  `os_dataInicio` VARCHAR(45) NOT NULL,
  `os_dataExpiracao` VARCHAR(45) NOT NULL,
  `os_descricao` VARCHAR(255) NOT NULL,
  `os_funcionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`os_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_bfg`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`tbl_usuario` (
  `usu_codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `usu_nome` VARCHAR(255) NOT NULL,
  `usu_sobreNome` VARCHAR(45) NOT NULL,
  `usu_senha` VARCHAR(45) NOT NULL,
  `usu_ativo` INT(1) NOT NULL,
  `log_login_LOG_CODIGO` INT(11) NOT NULL,
  PRIMARY KEY (`usu_codigo`),
  INDEX `fk_tbl_usuario_log_login_idx` (`log_login_LOG_CODIGO` ASC),
  CONSTRAINT `fk_tbl_usuario_log_login`
    FOREIGN KEY (`log_login_LOG_CODIGO`)
    REFERENCES `bd_bfg`.`log_login` (`LOG_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_bfg`.`tbl_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`tbl_pessoa` (
  `pes_id` INT(10) UNSIGNED NOT NULL,
  `pes_nome` VARCHAR(255) NOT NULL,
  `pes_email` VARCHAR(255) NOT NULL,
  `pes_senha` VARCHAR(255) NOT NULL,
  `pes_tipo` VARCHAR(11) NOT NULL,
  `tbl_usuario_usu_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`pes_id`),
  UNIQUE INDEX `pes_id_UNIQUE` (`pes_id` ASC),
  INDEX `fk_tbl_pessoa_tbl_usuario1_idx` (`tbl_usuario_usu_codigo` ASC),
  CONSTRAINT `fk_tbl_pessoa_tbl_usuario1`
    FOREIGN KEY (`tbl_usuario_usu_codigo`)
    REFERENCES `bd_bfg`.`tbl_usuario` (`usu_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_bfg`.`tbl_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_bfg`.`tbl_produto` (
  `pro_codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `pro_nome` VARCHAR(50) NOT NULL,
  `pro_preco` DOUBLE NOT NULL,
  `pro_quantidade` INT(11) NULL DEFAULT NULL,
  `pro_descricao` VARCHAR(255) NULL DEFAULT NULL,
  `pro_quantidadeMinima` INT(11) NOT NULL,
  `pro_foto` VARCHAR(255) NULL DEFAULT NULL,
  `pro_ativo` INT(1) NOT NULL,
  `tbl_estoque_est_codigo` INT(11) NOT NULL,
  `tbl_os_os_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`pro_codigo`),
  INDEX `fk_tbl_produto_tbl_estoque1_idx` (`tbl_estoque_est_codigo` ASC),
  INDEX `fk_tbl_produto_tbl_os1_idx` (`tbl_os_os_codigo` ASC),
  CONSTRAINT `fk_tbl_produto_tbl_estoque1`
    FOREIGN KEY (`tbl_estoque_est_codigo`)
    REFERENCES `bd_bfg`.`tbl_estoque` (`est_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_produto_tbl_os1`
    FOREIGN KEY (`tbl_os_os_codigo`)
    REFERENCES `bd_bfg`.`tbl_os` (`os_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
